// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS0SbH6CeytrZUkL_rKN64Rg5z9vzR4I4',
    appId: '1:915590349677:web:f248407bc57a831fdbd064',
    messagingSenderId: '915590349677',
    projectId: 'test-arai0907',
    authDomain: 'test-arai0907.firebaseapp.com',
    storageBucket: 'test-arai0907.appspot.com',
    measurementId: 'G-VESQVHN86M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKKB6XzFX7bdmHnVg3RfbGbPbmRFDD6xA',
    appId: '1:915590349677:android:9d6bc3b8243ef1d4dbd064',
    messagingSenderId: '915590349677',
    projectId: 'test-arai0907',
    storageBucket: 'test-arai0907.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuO_uGEJEBebviahzelcUyCmYWhrsWVz8',
    appId: '1:915590349677:ios:8449f348bf652db2dbd064',
    messagingSenderId: '915590349677',
    projectId: 'test-arai0907',
    storageBucket: 'test-arai0907.appspot.com',
    iosClientId: '915590349677-3cgbnvgtekt3u736bv05mdtllr902b42.apps.googleusercontent.com',
    iosBundleId: 'syscon-support.sysconDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuO_uGEJEBebviahzelcUyCmYWhrsWVz8',
    appId: '1:915590349677:ios:8449f348bf652db2dbd064',
    messagingSenderId: '915590349677',
    projectId: 'test-arai0907',
    storageBucket: 'test-arai0907.appspot.com',
    iosClientId: '915590349677-3cgbnvgtekt3u736bv05mdtllr902b42.apps.googleusercontent.com',
    iosBundleId: 'syscon-support.sysconDemo',
  );
}
